<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert([
            ['word' => 'time', 'w_spanish' => 'tiempo'],
            ['word' => 'person', 'w_spanish' => 'persona'],
            ['word' => 'year', 'w_spanish' => 'año'],
            ['word' => 'way', 'w_spanish' => 'camino'],
            ['word' => 'day', 'w_spanish' => 'día'],
            ['word' => 'thing', 'w_spanish' => 'cosa'],
            ['word' => 'man', 'w_spanish' => 'hombre'],
            ['word' => 'world', 'w_spanish' => 'mundo'],
            ['word' => 'life', 'w_spanish' => 'vida'],
            ['word' => 'hand', 'w_spanish' => 'mano'],
            ['word' => 'part', 'w_spanish' => 'parte'],
            ['word' => 'child', 'w_spanish' => 'niño'],
            ['word' => 'eye', 'w_spanish' => 'ojo'],
            ['word' => 'woman', 'w_spanish' => 'mujer'],
            ['word' => 'place', 'w_spanish' => 'lugar'],
            ['word' => 'job', 'w_spanish' => 'trabajo'],
            ['word' => 'week', 'w_spanish' => 'semana'],
            ['word' => 'case', 'w_spanish' => 'caso'],
            ['word' => 'point', 'w_spanish' => 'punto'],
            ['word' => 'government', 'w_spanish' => 'gobierno'],
            ['word' => 'company', 'w_spanish' => 'compañía'],
            ['word' => 'number', 'w_spanish' => 'número'],
            ['word' => 'group', 'w_spanish' => 'grupo'],
            ['word' => 'problem', 'w_spanish' => 'problema'],
            ['word' => 'fact', 'w_spanish' => 'hecho'],
            ['word' => 'be', 'w_spanish' => 'ser'],
            ['word' => 'have', 'w_spanish' => 'tener'],
            ['word' => 'do', 'w_spanish' => 'hacer'],
            ['word' => 'say', 'w_spanish' => 'decir'],
            ['word' => 'get', 'w_spanish' => 'obtener'],
            ['word' => 'make', 'w_spanish' => 'hacer'],
            ['word' => 'take', 'w_spanish' => 'tomar'],
            ['word' => 'see', 'w_spanish' => 'ver'],
            ['word' => 'come', 'w_spanish' => 'venir'],
            ['word' => 'look', 'w_spanish' => 'mirar'],
            ['word' => 'want', 'w_spanish' => 'querer'],
            ['word' => 'give', 'w_spanish' => 'dar'],
            ['word' => 'use', 'w_spanish' => 'usar'],
            ['word' => 'find', 'w_spanish' => 'encontrar'],
            ['word' => 'tell', 'w_spanish' => 'decir'],
            ['word' => 'ask', 'w_spanish' => 'preguntar'],
            ['word' => 'work', 'w_spanish' => 'trabajar'],
            ['word' => 'seem', 'w_spanish' => 'parecer'],
            ['word' => 'feel', 'w_spanish' => 'sentir'],
            ['word' => 'try', 'w_spanish' => 'intentar'],
            ['word' => 'leave', 'w_spanish' => 'dejar'],
            ['word' => 'call', 'w_spanish' => 'llamar'],
            ['word' => 'good', 'w_spanish' => 'bueno'],
            ['word' => 'new', 'w_spanish' => 'nuevo'],
            ['word' => 'first', 'w_spanish' => 'primero'],
            ['word' => 'last', 'w_spanish' => 'último'],
            ['word' => 'long', 'w_spanish' => 'largo'],
            ['word' => 'great', 'w_spanish' => 'gran'],
            ['word' => 'little', 'w_spanish' => 'pequeño'],
            ['word' => 'own', 'w_spanish' => 'propio'],
            ['word' => 'other', 'w_spanish' => 'otro'],
            ['word' => 'old', 'w_spanish' => 'viejo'],
            ['word' => 'right', 'w_spanish' => 'derecho'],
            ['word' => 'big', 'w_spanish' => 'grande'],
            ['word' => 'high', 'w_spanish' => 'alto'],
            ['word' => 'different', 'w_spanish' => 'diferente'],
            ['word' => 'small', 'w_spanish' => 'pequeño'],
            ['word' => 'large', 'w_spanish' => 'grande'],
            ['word' => 'next', 'w_spanish' => 'siguiente'],
            ['word' => 'early', 'w_spanish' => 'temprano'],
            ['word' => 'young', 'w_spanish' => 'joven'],
            ['word' => 'important', 'w_spanish' => 'importante'],
            ['word' => 'few', 'w_spanish' => 'pocos'],
            ['word' => 'public', 'w_spanish' => 'público'],
            ['word' => 'bad', 'w_spanish' => 'malo'],
            ['word' => 'same', 'w_spanish' => 'mismo'],
            ['word' => 'able', 'w_spanish' => 'capaz'],
            ['word' => 'to', 'w_spanish' => 'a'],
            ['word' => 'of', 'w_spanish' => 'de'],
            ['word' => 'in', 'w_spanish' => 'en'],
            ['word' => 'for', 'w_spanish' => 'para'],
            ['word' => 'on', 'w_spanish' => 'sobre'],
            ['word' => 'with', 'w_spanish' => 'con'],
            ['word' => 'at', 'w_spanish' => 'en'],
            ['word' => 'by', 'w_spanish' => 'por'],
            ['word' => 'from', 'w_spanish' => 'de'],
            ['word' => 'up', 'w_spanish' => 'arriba'],
            ['word' => 'into', 'w_spanish' => 'en'],
            ['word' => 'the', 'w_spanish' => 'el'],
            ['word' => 'and', 'w_spanish' => 'y'],
            ['word' => 'a', 'w_spanish' => 'un'],
            ['word' => 'that', 'w_spanish' => 'que'],
            ['word' => 'I', 'w_spanish' => 'yo'],
            ['word' => 'it', 'w_spanish' => 'eso'],
            ['word' => 'not', 'w_spanish' => 'no'],
            ['word' => 'he', 'w_spanish' => 'él'],
            ['word' => 'as', 'w_spanish' => 'como'],
            ['word' => 'you', 'w_spanish' => 'tú'],
            ['word' => 'this', 'w_spanish' => 'esto'],
            ['word' => 'but', 'w_spanish' => 'pero'],
            ['word' => 'his', 'w_spanish' => 'su'],
            ['word' => 'they', 'w_spanish' => 'ellos'],
            ['word' => 'her', 'w_spanish' => 'su'],
            ['word' => 'she', 'w_spanish' => 'ella'],
            ['word' => 'or', 'w_spanish' => 'o'],
            ['word' => 'an', 'w_spanish' => 'un'],
            ['word' => 'will', 'w_spanish' => 'voluntad'],
            ['word' => 'my', 'w_spanish' => 'mi'],
            ['word' => 'one', 'w_spanish' => 'uno'],
            ['word' => 'all', 'w_spanish' => 'todo'],
            ['word' => 'would', 'w_spanish' => 'sería'],
            ['word' => 'there', 'w_spanish' => 'allí'],
            ['word' => 'their', 'w_spanish' => 'su'],
            ['word' => 'what', 'w_spanish' => 'qué'],
            ['word' => 'so', 'w_spanish' => 'tan'],
            ['word' => 'out', 'w_spanish' => 'fuera'],
            ['word' => 'if', 'w_spanish' => 'si'],
            ['word' => 'about', 'w_spanish' => 'acerca de'],
            ['word' => 'who', 'w_spanish' => 'quién'],
            ['word' => 'which', 'w_spanish' => 'cual'],
            ['word' => 'go', 'w_spanish' => 'ir'],
            ['word' => 'me', 'w_spanish' => 'yo'],
            ['word' => 'when', 'w_spanish' => 'cuando'],
            ['word' => 'can', 'w_spanish' => 'puede'],
            ['word' => 'like', 'w_spanish' => 'gustar'],
            ['word' => 'no', 'w_spanish' => 'no'],
            ['word' => 'just', 'w_spanish' => 'sólo'],
            ['word' => 'him', 'w_spanish' => 'él'],
            ['word' => 'know', 'w_spanish' => 'saber'],
            ['word' => 'people', 'w_spanish' => 'gente'],
            ['word' => 'your', 'w_spanish' => 'tu'],
            ['word' => 'some', 'w_spanish' => 'algunos'],
            ['word' => 'could', 'w_spanish' => 'podría'],
            ['word' => 'them', 'w_spanish' => 'ellos'],
            ['word' => 'than', 'w_spanish' => 'que'],
            ['word' => 'then', 'w_spanish' => 'entonces'],
            ['word' => 'now', 'w_spanish' => 'ahora'],
            ['word' => 'only', 'w_spanish' => 'solo'],
            ['word' => 'its', 'w_spanish' => 'su'],
            ['word' => 'over', 'w_spanish' => 'sobre'],
            ['word' => 'think', 'w_spanish' => 'pensar'],
            ['word' => 'also', 'w_spanish' => 'también'],
            ['word' => 'back', 'w_spanish' => 'de vuelta'],
            ['word' => 'after', 'w_spanish' => 'después'],
            ['word' => 'two', 'w_spanish' => 'dos'],
            ['word' => 'how', 'w_spanish' => 'cómo'],
            ['word' => 'our', 'w_spanish' => 'nuestro'],
            ['word' => 'well', 'w_spanish' => 'bien'],
            ['word' => 'even', 'w_spanish' => 'incluso'],
            ['word' => 'because', 'w_spanish' => 'porque'],
            ['word' => 'any', 'w_spanish' => 'cualquier'],
            ['word' => 'these', 'w_spanish' => 'estos'],
            ['word' => 'most', 'w_spanish' => 'la mayoría'],
        ]);
    }
}
